### ISSUE TITLE
Proxy panics when arguments have not been specified

### ISSUE THREAD

**Issue by aeneasr** [ory/cli#75]
**Describe the bug**

```
$ ory proxy
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ory/cli/cmd/cloud/proxy.NewProxyCmd.func1(0xc000d98000, 0x63b5760, 0x0, 0x0, 0x0, 0x0)
	/Users/foobar/workspace/go/src/github.com/ory/cli/cmd/cloud/proxy/proxy.go:105 +0xbb6
github.com/spf13/cobra.(*Command).execute(0xc000d98000, 0x63b5760, 0x0, 0x0, 0xc000d98000, 0x63b5760)
	/Users/foobar/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d73b80, 0xc0007a1920, 0x52ce5e0, 0x57ba390)
	/Users/foobar/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/foobar/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/foobar/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/ory/cli/cmd.Execute()
	/Users/foobar/workspace/go/src/github.com/ory/cli/cmd/root.go:45 +0x106
main.main()
	/Users/foobar/workspace/go/src/github.com/ory/cli/main.go:8 +0x25
```

**Expected behavior**

No panic

**Environment**

- Version:   master

**Comment by zepatrik** [comment]
FYI @Demonsthere, cobra comes with arg validation functions already: https://github.com/spf13/cobra#positional-and-custom-arguments

**Comment by Demonsthere** [comment]
The [culprit](https://github.com/ory/cli/pull/74/commits/34b05981f52e7af3a026fcd704adf8d820977ec1#diff-5ebd1bbc8271f8d96ddd9bf0484b2da2a7ed86b064e238f8dab45c11e6f09324R54) has been found :)
